# Generated by Django 3.2.8 on 2021-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('occupant_count', models.IntegerField(null=True)),
            ],
        ),
    ]
