# Generated by Django 3.2.8 on 2022-01-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thehood', '0002_business_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='neighourhood',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
